import test from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import fs from "node:fs/promises";

import {
  createSdkEmceptionSession,
  EmceptionCompilerAdapter,
  SignedArtifactCatalog,
} from "../src/index.js";
import { SDK_EMCEPTION_SESSION_KIND } from "../src/compiler/sdkEmceptionSession.js";

async function readJson(relativePath) {
  const url = new URL(relativePath, import.meta.url);
  return JSON.parse(await fs.readFile(url, "utf8"));
}

function wasmBytes(seed) {
  return new Uint8Array([0x00, 0x61, 0x73, 0x6d, seed, seed + 1, seed + 2]);
}

test("emception compiler adapter prepares a single-source C++ compile plan with signed artifacts", async () => {
  const flow = await readJson("../examples/flows/iss-proximity-oem/flow.json");
  const catalog = new SignedArtifactCatalog();
  flow.artifactDependencies.forEach((dependency, index) => {
    catalog.registerArtifact({
      dependencyId: dependency.dependencyId,
      pluginId: dependency.pluginId,
      version: dependency.version,
      signature: dependency.signature,
      signerPublicKey: dependency.signerPublicKey,
      entrypoint: "main",
      runtimeExports: {
        initSymbol: "plugin_init",
        destroySymbol: "plugin_destroy",
        mallocSymbol: "malloc",
        freeSymbol: "free",
        streamInvokeSymbol: "plugin_stream_invoke",
      },
      wasm: wasmBytes(index + 1),
      manifestBuffer: new Uint8Array([0x50, 0x4c, 0x55, 0x47, index + 1]),
    });
  });

  const workingDirectory = `/working/compiler-test-${randomUUID()}`;
  const emception = await createSdkEmceptionSession({
    workingDirectory,
  });

  try {
    const compiler = new EmceptionCompilerAdapter({
      emception,
      artifactCatalog: catalog,
      manifestBuilder: async () =>
        new Uint8Array([0x46, 0x4c, 0x4f, 0x57, 0x31]),
    });

    const prepared = await compiler.prepareCompile({ program: flow });
    assert.equal(prepared.dependencies.length, 6);
    assert.equal(prepared.runtimeModel, "compiled-cpp-wasm");
    assert.equal(prepared.sourceGeneratorModel, "native-cpp-wasm");
    assert.equal(prepared.runtimeExports.mallocSymbol, "malloc");
    assert.equal(
      prepared.runtimeExports.descriptorSymbol,
      "sdn_flow_get_runtime_descriptor",
    );
    assert.equal(
      prepared.runtimeExports.ingressFrameDescriptorsSymbol,
      "sdn_flow_get_ingress_frame_descriptors",
    );
    assert.equal(
      prepared.runtimeExports.nodeDescriptorsSymbol,
      "sdn_flow_get_node_descriptors",
    );
    assert.equal(
      prepared.runtimeExports.nodeDispatchDescriptorsSymbol,
      "sdn_flow_get_node_dispatch_descriptors",
    );
    assert.equal(
      prepared.runtimeExports.prepareInvocationDescriptorSymbol,
      "sdn_flow_prepare_node_invocation_descriptor",
    );
    assert.equal(
      prepared.runtimeExports.externalInterfaceDescriptorsSymbol,
      "sdn_flow_get_external_interface_descriptors",
    );
    assert.equal(
      prepared.runtimeExports.enqueueTriggerSymbol,
      "sdn_flow_enqueue_trigger_frames",
    );
    assert.equal(
      prepared.runtimeExports.beginInvocationSymbol,
      "sdn_flow_begin_node_invocation",
    );
    assert.equal(
      prepared.runtimeExports.applyInvocationResultSymbol,
      "sdn_flow_apply_node_invocation_result",
    );
    assert.equal(
      prepared.runtimeExports.dispatchHostInvocationSymbol,
      "sdn_flow_dispatch_next_ready_node_with_host",
    );
    assert.equal(
      prepared.runtimeExports.drainWithHostDispatchSymbol,
      "sdn_flow_drain_with_host_dispatch",
    );
    assert.equal(
      prepared.runtimeExports.editorMetadataJsonSymbol,
      "sdn_flow_get_editor_metadata_json",
    );
    assert.equal(
      prepared.runtimeExports.editorMetadataSizeSymbol,
      "sdn_flow_get_editor_metadata_size",
    );
    assert.match(prepared.command, /\/working\/flow-runtime\.wasm$/);
    assert.match(
      prepared.source,
      /generated by the native sdn-flow C\+\+ source generator/,
    );
    assert.match(prepared.source, /flow_get_manifest_flatbuffer/);
    assert.match(prepared.source, /struct FlowRuntimeDescriptor/);
    assert.match(prepared.source, /struct FlowIngressDescriptor/);
    assert.match(prepared.source, /struct FlowIngressRuntimeState/);
    assert.match(prepared.source, /sdn_flow_get_runtime_descriptor/);
    assert.match(prepared.source, /kEditorMetadataJson/);
    assert.match(prepared.source, /sdn_flow_get_editor_metadata_json/);
    assert.match(prepared.source, /sdn_flow_get_editor_metadata_size/);
    assert.match(prepared.source, /sdn_flow_get_type_descriptors/);
    assert.match(prepared.source, /sdn_flow_get_trigger_descriptors/);
    assert.match(prepared.source, /sdn_flow_get_node_descriptors/);
    assert.match(prepared.source, /struct FlowNodeDispatchDescriptor/);
    assert.match(prepared.source, /struct FlowFrameDescriptor/);
    assert.match(prepared.source, /struct FlowInvocationDescriptor/);
    assert.match(prepared.source, /const char \* port_id/);
    assert.match(prepared.source, /kNodeDispatchDescriptors/);
    assert.match(prepared.source, /kIngressFrameDescriptors/);
    assert.match(prepared.source, /kCurrentInvocationDescriptor/);
    assert.match(prepared.source, /sdn_flow_get_node_dispatch_descriptors/);
    assert.match(prepared.source, /sdn_flow_get_ingress_frame_descriptors/);
    assert.match(prepared.source, /sdn_flow_get_current_invocation_descriptor/);
    assert.match(prepared.source, /sdn_flow_prepare_node_invocation_descriptor/);
    assert.match(prepared.source, /sdn_flow_enqueue_trigger_frame/);
    assert.match(prepared.source, /sdn_flow_enqueue_edge_frame/);
    assert.match(prepared.source, /stream-invoke/);
    assert.match(prepared.source, /plugin_stream_invoke/);
    assert.match(prepared.source, /sdn_flow_get_edge_descriptors/);
    assert.match(prepared.source, /sdn_flow_get_trigger_binding_descriptors/);
    assert.match(prepared.source, /sdn_flow_get_node_ingress_indices/);
    assert.match(prepared.source, /sdn_flow_get_external_interface_descriptors/);
    assert.match(prepared.source, /sdn_flow_reset_runtime_state/);
    assert.match(prepared.source, /sdn_flow_enqueue_trigger_frames/);
    assert.match(prepared.source, /sdn_flow_enqueue_edge_frames/);
    assert.match(prepared.source, /sdn_flow_get_ready_node_index/);
    assert.match(prepared.source, /sdn_flow_begin_node_invocation/);
    assert.match(prepared.source, /sdn_flow_complete_node_invocation/);
    assert.match(prepared.source, /sdn_flow_apply_node_invocation_result/);
    assert.match(prepared.source, /kIngressDescriptors/);
    assert.match(prepared.source, /kIngressRuntimeStates/);
    assert.match(prepared.source, /kNodeIngressIndices/);
    assert.match(prepared.source, /kNodeRuntimeStates/);
    assert.match(prepared.source, /sdn_flow_get_dependency_descriptors/);
    assert.match(prepared.source, /com\.digitalarsenal\.flatsql\.store/);
    assert.match(prepared.command, /_sdn_flow_get_runtime_descriptor/);
    assert.match(prepared.command, /_malloc/);
    assert.match(prepared.command, /_free/);
    assert.match(prepared.command, /_sdn_flow_get_node_descriptors/);
    assert.match(prepared.command, /_sdn_flow_get_node_dispatch_descriptors/);
    assert.match(prepared.command, /_sdn_flow_get_ingress_frame_descriptors/);
    assert.match(
      prepared.command,
      /_sdn_flow_prepare_node_invocation_descriptor/,
    );
    assert.match(
      prepared.command,
      /_sdn_flow_get_external_interface_descriptors/,
    );
    assert.match(prepared.command, /_sdn_flow_reset_runtime_state/);
    assert.match(prepared.command, /_sdn_flow_enqueue_trigger_frames/);
    assert.match(prepared.command, /_sdn_flow_begin_node_invocation/);
    assert.match(prepared.command, /_sdn_flow_apply_node_invocation_result/);

    const artifact = await compiler.compile({ program: flow });
    assert.equal(artifact.programId, flow.programId);
    assert.equal(artifact.runtimeModel, "compiled-cpp-wasm");
    assert.equal(artifact.sourceGeneratorModel, "native-cpp-wasm");
    assert.equal(
      artifact.runtimeExports.descriptorSymbol,
      "sdn_flow_get_runtime_descriptor",
    );
    assert.equal(artifact.runtimeExports.freeSymbol, "free");
    assert.equal(
      artifact.runtimeExports.typeDescriptorsSymbol,
      "sdn_flow_get_type_descriptors",
    );
    assert.equal(
      artifact.runtimeExports.nodeIngressIndicesSymbol,
      "sdn_flow_get_node_ingress_indices",
    );
    assert.equal(
      artifact.runtimeExports.nodeDispatchDescriptorCountSymbol,
      "sdn_flow_get_node_dispatch_descriptor_count",
    );
    assert.equal(
      artifact.runtimeExports.currentInvocationDescriptorSymbol,
      "sdn_flow_get_current_invocation_descriptor",
    );
    assert.equal(
      artifact.runtimeExports.readyNodeSymbol,
      "sdn_flow_get_ready_node_index",
    );
    assert.equal(
      artifact.runtimeExports.applyInvocationResultSymbol,
      "sdn_flow_apply_node_invocation_result",
    );
    assert.equal(
      artifact.runtimeExports.dispatchHostInvocationSymbol,
      "sdn_flow_dispatch_next_ready_node_with_host",
    );
    assert.equal(
      artifact.runtimeExports.drainWithHostDispatchSymbol,
      "sdn_flow_drain_with_host_dispatch",
    );
    assert.equal(
      artifact.runtimeExports.editorMetadataJsonSymbol,
      "sdn_flow_get_editor_metadata_json",
    );
    assert.equal(
      artifact.runtimeExports.editorMetadataSizeSymbol,
      "sdn_flow_get_editor_metadata_size",
    );
    assert.equal(artifact.pluginVersions.length, 6);
    assert.equal(artifact.requiredCapabilities.includes("storage_query"), true);
    assert.equal(artifact.requiredCapabilities.includes("pubsub"), true);
    assert.ok(artifact.wasm instanceof Uint8Array);
    assert.equal(artifact.loaderModule.includes("export default"), true);
  } finally {
    await emception.removeDirectory(workingDirectory).catch(() => {});
    await emception.dispose().catch(() => {});
  }
});

test("emception compiler adapter rejects artifact compilation without an SDK emception session", async () => {
  const flow = await readJson("../examples/flows/iss-proximity-oem/flow.json");
  const compiler = new EmceptionCompilerAdapter({
    artifactCatalog: {
      async resolveProgramDependencies() {
        return [];
      },
    },
    manifestBuilder: async () => new Uint8Array([0x46, 0x4c, 0x4f, 0x57, 0x31]),
  });

  await assert.rejects(
    compiler.compile({ program: flow }),
    /Artifact compilation requires an SDK emception session/,
  );
});

test("emception compiler adapter rejects SDK-labeled impostor sessions for artifact compilation", async () => {
  const flow = await readJson("../examples/flows/iss-proximity-oem/flow.json");
  const compiler = new EmceptionCompilerAdapter({
    artifactCatalog: {
      async resolveProgramDependencies() {
        return [];
      },
    },
    emception: {
      sessionKind: SDK_EMCEPTION_SESSION_KIND,
      async init() {},
      async writeFile() {},
      async readFile() {
        return new Uint8Array([0x00, 0x61, 0x73, 0x6d]);
      },
      async run() {
        return {
          returncode: 0,
          stdout: "",
          stderr: "",
        };
      },
    },
    manifestBuilder: async () => new Uint8Array([0x46, 0x4c, 0x4f, 0x57, 0x31]),
  });

  await assert.rejects(
    compiler.compile({ program: flow }),
    /only supports SDK emception sessions/,
  );
});
