import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { compileNodeRedFlowsToSdnArtifact } from "../src/editor/compileArtifact.js";
import { resolveSdnFlowEditorCompileArtifactScriptPath } from "../src/editor/compileArtifactSubprocess.js";
import { SDK_EMCEPTION_SESSION_KIND } from "../src/compiler/sdkEmceptionSession.js";

test("compileNodeRedFlowsToSdnArtifact lowers editor flows into a serialized compiled artifact payload", async () => {
  const result = await compileNodeRedFlowsToSdnArtifact(
    [
      {
        id: "flow-1",
        type: "tab",
        label: "Flow 1",
      },
      {
        id: "inject-1",
        z: "flow-1",
        type: "inject",
        x: 100,
        y: 80,
        wires: [["debug-1"]],
      },
      {
        id: "debug-1",
        z: "flow-1",
        type: "debug",
        x: 240,
        y: 80,
        wires: [],
      },
    ],
    {
      outputName: "flow-runtime",
    },
  );

  assert.equal(result.outputName, "flow-runtime");
  assert.equal(result.runtimeModel, "compiled-cpp-wasm");
  assert.equal(result.sourceGeneratorModel, "native-cpp-wasm");
  assert.match(result.source, /generated by the native sdn-flow C\+\+ source generator/);
  assert.equal(result.serializedArtifact.programId, "flow-1");
  assert.match(result.serializedArtifact.wasmBase64, /^AGFzbQ/);
  assert.equal(result.artifactSummary.programId, "flow-1");
  assert.equal(result.artifactSummary.runtimeModel, "compiled-cpp-wasm");
  assert.ok(result.artifactSummary.wasmBytes > 4);
  assert.equal(result.program.triggers[0].triggerId, "trigger-inject-1");
  assert.equal(result.deploymentPlan.pluginId, "flow-1");
  assert.equal(result.deploymentPlan.scheduleBindings.length, 0);
});

test("compile artifact subprocess always resolves the packaged helper script", async () => {
  const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), "sdn-flow-editor-artifact-script-"));
  const scriptPath = path.join(tempDir, "scripts", "editor-compile-artifact.mjs");
  const packagedScriptPath = fileURLToPath(
    new URL("../scripts/editor-compile-artifact.mjs", import.meta.url),
  );

  try {
    await fs.mkdir(path.dirname(scriptPath), { recursive: true });
    await fs.writeFile(scriptPath, "export {};\n", "utf8");

    assert.equal(
      resolveSdnFlowEditorCompileArtifactScriptPath({
        cwd: tempDir,
      }),
      packagedScriptPath,
    );
  } finally {
    await fs.rm(tempDir, { recursive: true, force: true });
  }
});

test("compileNodeRedFlowsToSdnArtifact derives delegated HTTP service bindings from http-in triggers", async () => {
  const result = await compileNodeRedFlowsToSdnArtifact(
    [
      {
        id: "flow-1",
        type: "tab",
        label: "Flow 1",
      },
      {
        id: "http-in-1",
        z: "flow-1",
        type: "http in",
        method: "get",
        url: "/catalog",
        wires: [["debug-1"]],
      },
      {
        id: "debug-1",
        z: "flow-1",
        type: "debug",
        wires: [],
      },
    ],
    {
      serviceBindingMode: "delegated",
      delegatedServiceBaseUrl: "https://gateway.example.test/base/",
      defaultHttpAuthPolicyId: "approved-keys",
      deploymentPlan: {
        authPolicies: [
          {
            policyId: "approved-keys",
            bindingMode: "delegated",
            targetKind: "service",
            targetId: "service-trigger-http-in-1",
            allowServerKeys: ["ed25519:test-key"],
          },
        ],
      },
    },
  );

  assert.equal(result.deploymentPlan.serviceBindings.length, 1);
  assert.deepEqual(result.deploymentPlan.serviceBindings[0], {
    serviceId: "service-trigger-http-in-1",
    bindingMode: "delegated",
    serviceKind: "http-server",
    triggerId: "trigger-http-in-1",
    protocolId: null,
    routePath: "/catalog",
    method: "GET",
    transportKind: null,
    adapter: null,
    listenHost: null,
    listenPort: 0,
    remoteUrl: "https://gateway.example.test/catalog",
    allowTransports: ["https", "wss"],
    authPolicyId: "approved-keys",
    description: "[GET] /catalog",
    properties: {},
  });
});

test("compileNodeRedFlowsToSdnArtifact rejects direct compiler overrides for artifact builds", async () => {
  await assert.rejects(
    compileNodeRedFlowsToSdnArtifact(
      [
        {
          id: "flow-1",
          type: "tab",
          label: "Flow 1",
        },
      ],
      {
        compiler: {
          async compile() {
            throw new Error("should not be called");
          },
        },
      },
    ),
    /Artifact compilation no longer accepts compiler overrides/,
  );
});

test("compileNodeRedFlowsToSdnArtifact rejects custom emception session factories even when SDK-marked", async () => {
  await assert.rejects(
    compileNodeRedFlowsToSdnArtifact(
      [
        {
          id: "flow-1",
          type: "tab",
          label: "Flow 1",
        },
      ],
      {
        emceptionSessionFactory: async () => ({
          sessionKind: SDK_EMCEPTION_SESSION_KIND,
          async init() {},
          async writeFile() {},
          async readFile() {
            return new Uint8Array([0x00, 0x61, 0x73, 0x6d]);
          },
          async run() {
            return {
              returncode: 0,
              stdout: "",
              stderr: "",
            };
          },
          async removeDirectory() {},
        }),
      },
    ),
    /no longer accepts custom emceptionSessionFactory overrides/,
  );
});

test("compileNodeRedFlowsToSdnArtifact rejects sourceGenerator overrides for artifact builds", async () => {
  await assert.rejects(
    compileNodeRedFlowsToSdnArtifact(
      [
        {
          id: "flow-1",
          type: "tab",
          label: "Flow 1",
        },
      ],
      {
        sourceGenerator: async () => ({
          source: "int main() { return 0; }\n",
          generatorModel: "test-generator",
        }),
      },
    ),
    /no longer accepts sourceGenerator overrides/,
  );
});
